### ISSUE TITLE
Bid information: Will the standard cover details of the companies who bid?

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting-archive/process-documentation#1]
In early exploration we considered what information might be made available about the companies who bid for a contract. 

I'm currently reviewing the Philippines Open Govt Partnership Self Assessment report regards PhilGEPS, and they note "The implementation of E-Bidding ... was delayed due to a policy discussion concerning the disclosure of companies that obtain bid documents. It was eventually decided to only disclose the number of companies that obtained bid documents without listing their identities, to lower the probability of collusion between companies."

Some questions this may raise:
- What should a standard capture and encourage to be shared with respect to information on companies bidding?
- Are there any use cases which require information on firms who bid (but were unsuccessful)?
- Is a count of firms bidding for a contract a useful data point for any of our use cases?
- Are there was of anonymising the details of the firms that bid, whilst still meeting use cases that might want information of this form?

**Comment by jpmckinney** [comment]
Logging that much work has been done on this since the issue was created.
